### ISSUE TITLE
HttpListener can sometimes crash when starting to listen

### ISSUE THREAD

**Issue by stevehobbsdev** [Orchidsoft/vs-net-dte#1]
Log from Event Log:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.HttpListenerException
Stack:
   at System.Net.HttpListener.Start()
   at NetDTE.RequestListener.Listen()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by stevehobbsdev** [comment]
v0.5 removes the HTTP handler in favour of `FileSystemWatcher`
